module similarTriangles_gameplay_example{
//The Background Theory declaring all relevant types and functions
type point
type triangle = (point,point,point)
dist: point -> point -> float
similar: triangle -> triangle -> bool
/////

/////
// The facts all have useful names. They certainly wouldn't be generated this way, so let's just claim the user can rename them. 
/////

theory S1{
  //             tip
  //           ,´ |
  //          p   |
  //        ,´|   |
  //  ground--q--foot
  tip: point = ???
  foot: point = ???
  ground: point = ???
  p: point = ???
  q: point = ???
  ground_dist_small = 42
  ground_dist_small_P:  |- dist(ground)(q) == ground_dist_small = ???
  ground_dist_large = 420
  ground_dist_large_P:  |- dist(ground)(foot) == ground_dist_large = ???
  apparent_height = 21
  apparent_height_P: |- dist(q)(p) == apparent_height = ???
  are_similar: |- similar((tip,ground,foot))((p, ground, q)) = ???
}

theory _simTri_Scroll{
  //             A
  //           ,´|
  //          B  |
  //        ,´|  |
  //       C--D--E

  _A: point
  _B: point
  _C: point
  _D: point
  _E: point
  _CD: float
  _CD_P:  |- dist(_C)(_D) == _CD
  _CE: float
  _CE_P:  |- dist(_C)(_E) == _CE
  _DB: float
  _DB_P: |- dist(_D)(_B) == _DB
  _are_similar: |- similar((_A,_C,_E))((_B,_C,_D)) 

  // The solution of the scroll. Recognizable by 
  // - having a definiens (hypothetically)
  // - starting with a double underscore
  __EA = _CE * _DB / _CD
  __EA_P: |- dist(_E)(_A) == __EA = ???
}

// ///////////
// // Approach 1: Equate the Slots in a temporary Theory
// // 1. Generate `Slot_equations`
// // 2. `solve()` the `Slot_equations`, and
// // 3. Adequately rename the solution(s)
// // 4. `S3_1` is generated by removing all helper declarations (i.e. everything involving a name starting with an underscore) from the result
// //////////

theory Slot_equations{
  include S1
  realize _simTri_Scroll
  _A = tip
  _B = p
  _C = ground
  _D = q
  _E = foot
  _CD = ground_dist_small
  _CD_P = ground_dist_small_P
  _CE = ground_dist_large
  _CE_P = ground_dist_large_P
  _DB = apparent_height
  _DB_P = apparent_height_P
  _are_similar = are_similar
}

theory S2{
  include S1
  tree_height = Slot_equations{}.__EA
  tree_height_P = Slot_equations{}.__EA_P
}

test = S2{ }.tree_height
}